version: '3.7'

services:
    id.dev.tylery.org:
        labels:
            caddy: id.dev.lan
            caddy.reverse_proxy: "{{ upstreams 8000 }}"
        build: 
            context: .
            target: dev
        volumes:
            - ./app:/app
        networks:
            - caddy

networks:
    caddy:
        external: true
