version: '3.7'

services:
    django_app:
        environment:
            - HOST
            - DEBUG
            - LOG
            - SECRET_KEY
            - USER=${USER}
            - PORT=8000
        logging:
            driver: "json-file"
        labels:
            caddy: ${HOST}
            caddy.reverse_proxy: "{{ upstreams 8000 }}"
#       image: ghcr.io/tyler71/id_django:latest
        build:
            context: .
            target: prod
#       volumes:
#           - ./app:/app
        networks:
            - public

networks:
  public:
    external: true
