version: '3.7'

services:
    id.dev.tylery.org:
        environment:
            - HOST
            - DEBUG
            - SECRET_KEY
        labels:
            caddy: ${HOST}
            caddy.reverse_proxy: "{{ upstreams 8000 }}"
        build: 
            context: .
            target: dev
        volumes:
            - ./app:/app
        networks:
            - caddy

networks:
    caddy:
        external: true
