version: '3.7'

services:
    django_app:
        environment:
            - HOST
            - DEBUG=False
            - LOG
            - SECRET_KEY
        labels:
            caddy: ${HOST}
            caddy.reverse_proxy: "{{ upstreams 8000 }}"
        build:
            context: .
            target: prod
        networks:
            - caddy

networks:
    caddy:
        external: true
