version: '3.7'

services:
    django_app:
        environment:
            - HOST
            - DEBUG
            - LOG
            - SECRET_KEY
            - USER=${USER}
        labels:
            caddy: ${HOST}
            caddy.reverse_proxy: "{{ upstreams 8000 }}"
#       image: ghcr.io/tyler71/id_django:latest
        build:
            context: .
            target: prod
#       volumes:
#           - ./app:/app
        networks:
            - caddy

networks:
    caddy:
        external: true
