# fly.toml file generated for image-difference on 2022-08-25T22:10:20Z

app = "image-difference"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

  PORT=8000

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[build]
  build-target = "prod"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    force_https = false
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
