# Generated by Django 3.0.3 on 2020-11-12 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=100)),
                ('images_used', models.IntegerField()),
                ('submitted', models.DateTimeField()),
                ('conversion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='convertimage.ConversionType')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField()),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='pending_conversion')),
                ('imageunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convertimage.ImageUnit')),
            ],
        ),
        migrations.AddField(
            model_name='imageunit',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convertimage.Users'),
        ),
    ]
