# Generated by Django 3.0.3 on 2020-11-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.ImageField(upload_to='imgs')),
                ('images_used', models.IntegerField()),
                ('conversion', models.CharField(max_length=20)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('img_hash', models.CharField(max_length=50)),
            ],
        ),
    ]
