name: build_image

on:
  create:
    tags:
      - "v*.*.*"
  push:
    branch:
      - master

jobs:
  private-registry-tag:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get tagname
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        name: Tag variables
        id: vars
        run: |
            echo ::set-output name=major_version::$(echo ${{ steps.tag.outputs.tag }} | cut -d'.' -f1)
            echo ::set-output name=minor_version::$(echo ${{ steps.tag.outputs.tag }} | cut -d'.' -f1-2)
            echo ::set-output name=patch_version::$(echo ${{ steps.tag.outputs.tag }} | cut -d'.' -f1-3)
      -
        name: Login to private registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY }}
          username: build_push_api
          password: ${{ secrets.BUILD_PUSH_API }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push latest [latest]
        if: startswith(github.ref, 'refs/heads/master')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.PRIVATE_REGISTRY }}/name/app:latest
          target: prod
      -
        name: Build and push major [v1]
        if: startswith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.PRIVATE_REGISTRY }}/name/app:${{ steps.vars.outputs.major_version }}
          target: prod
      -
        name: Build and push minor [v1.2]
        if: startswith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.PRIVATE_REGISTRY }}/name/app:${{ steps.vars.outputs.minor_version }}
          target: prod
      -
        name: Build and push patch [v1.2.3]
        if: startswith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.PRIVATE_REGISTRY }}/name/app:${{ steps.vars.outputs.patch_version }}
          target: prod
