name: Build and deploy to heroku

on:
# create:
#   tags:
#     - "v*.*.*"
  push:
    branch:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Login to Heroku
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: _
          password: ${{secrets.HEROKU_API_KEY}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context:    .
          target:     prod
          push:       true
          tags:       registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/web
          cache-from: type=gha
          cache-to:   type=gha,mode=max

